### ISSUE TITLE
error in bake: list index out of range

### ISSUE THREAD

**Issue by lhmd** [Tugcga/Path-Finder#17]
I have met this problem in baking:
```
Traceback (most recent call last):
  File "test.py", line 85, in <module>
    baker.bake(
  File "/mnt/data3/home/wangweijie/miniconda3/envs/text2motion/lib/python3.8/site-packages/pathfinder/navmesh_baker/__init__.py", line 142, in bake
    is_build_contours = build_contours(chf, max_simplification_error, max_edge_len, cset)
  File "/mnt/data3/home/wangweijie/miniconda3/envs/text2motion/lib/python3.8/site-packages/pathfinder/navmesh_baker/rc_contour.py", line 814, in build_contours
    cont: Contour = cset.conts[cset.nconts]
IndexError: list index out of range
```
This is my code:
```
baker = nmb.NavmeshBaker()
    scene.apply_transform(zup_to_shapenet)
    vert_wo_color = scene.vertices.tolist()
    vert_wo_color = [tuple(vert) for vert in vert_wo_color]
    scene_face = scene.faces.tolist()
    # print(len(vert_wo_color), len(scene_face))
    baker.add_geometry(vert_wo_color, scene_face)
    baker.bake(
        verts_per_poly=3,
        cell_size=0.05, cell_height=0.05,
        agent_radius=0.05, agent_height=0.5, 
        agent_max_climb=0.1, agent_max_slope=15.0,
        # region_min_size=8, region_merge_size=20
    )
```
While some scenes is ok, but a few of scenes will meet this problem, I don't understand how it occur. Can everyone help me?

**Comment by Tugcga** [comment]
It will be better if you send me data with vertex coordinates and polygons of your scene. May be by using simple txt-file. I will try to understand, why it happens and is you PR is solve the problem.

**Comment by lhmd** [comment]
Sorry for not replying to you two days ago for some other personal reasons.
I am attaching the code I used and the file used to generate the navmesh so
you can try to reproduce my error. I haven't analysed the exact cause yet,
but I think it's due to mishandling of the conts in the rc_contour.py file.
I hope you will keep me informed if you have any new developments. Thank
you very much for your attention!

The .ply file in the reply email just now was too big, I put it on google
drive, please check it out.
https://drive.google.com/file/d/1QX8TfoTbCVgMsoNid7lzeuk_iBl_jk1E/view?usp=sharing

Tugcga ***@***.***> 于2024年5月21日周二 23:15写道：

**Comment by lhmd** [comment]
> It will be better if you send me data with vertex coordinates and polygons of your scene. May be by using simple txt-file. I will try to understand, why it happens and is you PR is solve the problem.

For privacy reasons, I've sent you the data and code I'm using using using email, so please check out. I haven't analysed the exact cause yet, but I think it's due to mishandling of the conts in the rc_contour.py file. Thank you very much for your attention!

**Comment by Tugcga** [comment]
Thank you very much. I need some time for research.

**Comment by Tugcga** [comment]
I am sorry for delay of the answer, but I finally find the time to check the bug. And I fail to reproduce it. This is your original model
![level_original](https://github.com/Tugcga/Path-Finder/assets/38164660/ce63dd2b-a8e2-4786-ade7-38cd36ae18ba)
It has some rotation and the baking process return an empty mesh.

After rotation it looks like this
![level_tfm](https://github.com/Tugcga/Path-Finder/assets/38164660/c5f9d04c-51be-419f-b56c-bfc1a8f8841e)

Then I bake the navmesh with your parameters:
```
baker.bake(verts_per_poly=3,
               cell_size=0.05,
               cell_height=0.05,
               agent_radius=0.05,
               agent_height=0.5,
               agent_max_climb=0.1,
               agent_max_slope=15.0)
```
and obtain the mesh without any errors (selected mesh on the screen)
![level_navmesh](https://github.com/Tugcga/Path-Finder/assets/38164660/740f0b7f-1794-4709-b6a0-85bf226d7bb9)

The navmesh contains 134 vertices and 124 triangles.
