### ISSUE TITLE
pip install pynavmesh

### ISSUE THREAD

**Issue by unwave** [Tugcga/Path-Finder#6]
`pip install pynavmesh` gives the next files structure:

```
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh\
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pynavmesh-1.2.2.dist-info\
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\
```

<details>
  <summary>All paths</summary>

```
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh\__init__.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh\__pycache__\__init__.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh\__pycache__\navmesh_bvh.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh\__pycache__\navmesh_graph.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh\__pycache__\navmesh_node.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh\navmesh_bvh.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh\navmesh_graph.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh\navmesh_node.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__init__.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__pycache__\__init__.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__pycache__\rc_area.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__pycache__\rc_calcs.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__pycache__\rc_classes.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__pycache__\rc_constants.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__pycache__\rc_contour.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__pycache__\rc_filtering.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__pycache__\rc_heightfield.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__pycache__\rc_mesh.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\__pycache__\rc_rasterization.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\rc_area.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\rc_calcs.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\rc_classes.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\rc_constants.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\rc_contour.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\rc_filtering.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\rc_heightfield.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\rc_mesh.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\navmesh_baker\rc_rasterization.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pynavmesh-1.2.2.dist-info\INSTALLER
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pynavmesh-1.2.2.dist-info\LICENSE
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pynavmesh-1.2.2.dist-info\METADATA
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pynavmesh-1.2.2.dist-info\RECORD
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pynavmesh-1.2.2.dist-info\REQUESTED
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pynavmesh-1.2.2.dist-info\WHEEL
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pynavmesh-1.2.2.dist-info\top_level.txt
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\__init__.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\__pycache__\__init__.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\__pycache__\agent.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\__pycache__\kd_tree.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\__pycache__\obstacle.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\__pycache__\rvo_simulator.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\__pycache__\utilities.cpython-39.pyc
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\agent.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\kd_tree.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\obstacle.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\rvo_simulator.py
C:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyrvo\utilities.py
```
</details>

So this does not resolve:
```python
from pathfinder import navmesh_baker as nmb
``` 

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pathfinder'
```

```cmd
Microsoft Windows [Version 10.0.19044.2006]
(c) Microsoft Corporation. All rights reserved.

C:\Users\user>python
Python 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathfinder import navmesh_baker as nmb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pathfinder'
>>> import navmesh_baker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\navmesh_baker\__init__.py", line 4, in <module>
    from pathfinder.navmesh_baker.rc_calcs import calc_grid_size
ModuleNotFoundError: No module named 'pathfinder'
>>> import navmesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\navmesh\__init__.py", line 3, in <module>
    from pathfinder.navmesh.navmesh_graph import NavmeshGraph
ModuleNotFoundError: No module named 'pathfinder'
>>> import pyrvo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrvo\__init__.py", line 9, in <module>
    from pathfinder.pyrvo.rvo_simulator import RVOSimulator
ModuleNotFoundError: No module named 'pathfinder'
>>>
```

**Comment by Tugcga** [comment]
Thank you very much. There was some errors in the configuration for building distributive for the pip. Now it fixed. You can install the fixed version by ```pip install pynavmesh==1.2.3```. Or may be it will install the ```1.2.3``` version by default.
